import type { CanvasItem } from '../types/canvas';

export interface BoardTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  elements: CanvasItem[];
}

export const BOARD_TEMPLATES: BoardTemplate[] = [
  {
    id: 'architecture',
    name: 'Distributed Cloud Architecture',
    category: 'Engineering',
    description: 'Microservices, P2P mesh, edge caching & database replication topology',
    elements: [
      // Client Tier
      {
        id: 'arch_client_1',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 60,
        y: 120,
        width: 170,
        height: 100,
        fillColor: 'rgba(56, 189, 248, 0.12)',
        strokeColor: '#38bdf8',
        strokeWidth: 2,
        label: '🖥️ Web / Mobile Clients',
        zIndex: 1,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      // Edge / CDN
      {
        id: 'arch_edge',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 320,
        y: 120,
        width: 180,
        height: 100,
        fillColor: 'rgba(168, 85, 247, 0.12)',
        strokeColor: '#a855f7',
        strokeWidth: 2,
        label: '⚡ Cloudflare Edge & Signaling',
        zIndex: 2,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      // WebRTC Mesh Node
      {
        id: 'arch_p2p',
        type: 'shape',
        shapeType: 'circle',
        x: 590,
        y: 90,
        width: 160,
        height: 160,
        fillColor: 'rgba(16, 185, 129, 0.12)',
        strokeColor: '#10b981',
        strokeWidth: 2,
        label: '🌐 P2P Mesh\n(Zero Server)',
        zIndex: 3,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      // Local IndexedDB
      {
        id: 'arch_idb',
        type: 'shape',
        shapeType: 'diamond',
        x: 320,
        y: 290,
        width: 180,
        height: 130,
        fillColor: 'rgba(245, 158, 11, 0.12)',
        strokeColor: '#f59e0b',
        strokeWidth: 2,
        label: '💾 IndexedDB Local-First',
        zIndex: 4,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      // Note
      {
        id: 'arch_sticky',
        type: 'sticky',
        x: 60,
        y: 290,
        width: 200,
        height: 140,
        color: '#fef08a',
        text: '📌 Local-First Guarantee:\nReads/writes execute with 0ms latency against local CRDT doc. Replicas merge via state vectors.',
        zIndex: 5,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      // Connectors
      {
        id: 'arch_arr_1',
        type: 'arrow',
        startX: 230,
        startY: 170,
        endX: 320,
        endY: 170,
        strokeColor: '#38bdf8',
        strokeWidth: 2.5,
        arrowEnd: true,
        label: 'WebSockets',
        x: 230,
        y: 170,
        width: 90,
        height: 10,
        zIndex: 6,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
      {
        id: 'arch_arr_2',
        type: 'arrow',
        startX: 500,
        startY: 170,
        endX: 590,
        endY: 170,
        strokeColor: '#10b981',
        strokeWidth: 2.5,
        arrowEnd: true,
        label: 'WebRTC DataChannel',
        x: 500,
        y: 170,
        width: 90,
        height: 10,
        zIndex: 7,
        createdBy: 'Architect',
        authorName: 'Architect',
        updatedAt: Date.now(),
      },
    ],
  },
  {
    id: 'sprint_retro',
    name: 'Agile Sprint Retrospective',
    category: 'Productivity',
    description: 'Team retrospective board with column categories and action items',
    elements: [
      // Column 1: What went well
      {
        id: 'retro_h1',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 50,
        y: 50,
        width: 240,
        height: 50,
        fillColor: 'rgba(16, 185, 129, 0.2)',
        strokeColor: '#10b981',
        strokeWidth: 2,
        label: '🌟 What Went Well',
        zIndex: 1,
        createdBy: 'Team Lead',
        authorName: 'Team Lead',
        updatedAt: Date.now(),
      },
      {
        id: 'retro_s1',
        type: 'sticky',
        x: 50,
        y: 120,
        width: 240,
        height: 120,
        color: '#bbf7d0',
        text: 'CRDT peer sync latency dropped below 15ms across all tabs! 🚀',
        zIndex: 2,
        createdBy: 'Engineer',
        authorName: 'Alex',
        updatedAt: Date.now(),
      },
      {
        id: 'retro_s2',
        type: 'sticky',
        x: 50,
        y: 260,
        width: 240,
        height: 120,
        color: '#bbf7d0',
        text: 'Time Machine scrubber visual replay feature has 100% test coverage.',
        zIndex: 3,
        createdBy: 'QA',
        authorName: 'Elena',
        updatedAt: Date.now(),
      },

      // Column 2: What to improve
      {
        id: 'retro_h2',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 330,
        y: 50,
        width: 240,
        height: 50,
        fillColor: 'rgba(245, 158, 11, 0.2)',
        strokeColor: '#f59e0b',
        strokeWidth: 2,
        label: '🛠️ What to Polish',
        zIndex: 4,
        createdBy: 'Team Lead',
        authorName: 'Team Lead',
        updatedAt: Date.now(),
      },
      {
        id: 'retro_s3',
        type: 'sticky',
        x: 330,
        y: 120,
        width: 240,
        height: 120,
        color: '#fef08a',
        text: 'High-DPI canvas zoom needs smoother wheel dampening on trackpads.',
        zIndex: 5,
        createdBy: 'Designer',
        authorName: 'Marcus',
        updatedAt: Date.now(),
      },

      // Column 3: Action Items
      {
        id: 'retro_h3',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 610,
        y: 50,
        width: 240,
        height: 50,
        fillColor: 'rgba(56, 189, 248, 0.2)',
        strokeColor: '#38bdf8',
        strokeWidth: 2,
        label: '🎯 Action Items',
        zIndex: 6,
        createdBy: 'Team Lead',
        authorName: 'Team Lead',
        updatedAt: Date.now(),
      },
      {
        id: 'retro_s4',
        type: 'sticky',
        x: 610,
        y: 120,
        width: 240,
        height: 130,
        color: '#bfdbfe',
        text: '1. Ship high-res PNG export\n2. Add sound effects synthesizer\n3. Connect portfolio showcase mode',
        zIndex: 7,
        createdBy: 'Engineer',
        authorName: 'Dev',
        updatedAt: Date.now(),
      },
    ],
  },
];
